name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày lúc 0:00 UTC
  workflow_dispatch: # chạy thủ công được

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake SVG (all years)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-2023.svg?year=2023
            dist/github-contribution-grid-snake-2024.svg?year=2024
            dist/github-contribution-grid-snake-2025.svg?year=2025

      - name: Push output to branch `output`
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
